version: '2.0'

services:
  myproject:
     image: seigott/burger_war_docker
     container_name: burger_war_docker
     ports:
      - "6081:80"
     shm_size: '512m'
     volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
     environment:
      - DISPLAY=unix${DISPLAY}
